import PDFDocument from "pdfkit";

interface PageSummary {
  pageUrl: string;
  events: number;
  avgSeverity: number;
}

export interface ExportPdfReportData {
  reportType: string;
  userId: string;
  generatedAt: Date;
  startDate?: Date;
  endDate?: Date;
  totalEvents: number;
  totalErrors: number;
  criticalErrors: number;
  averageSeverity: number;
  topPages: PageSummary[];
}

const formatDate = (value: Date | undefined): string => {
  if (!value) {
    return "N/A";
  }

  return value.toISOString().replace("T", " ").slice(0, 19);
};

export const renderExportPdf = async (data: ExportPdfReportData): Promise<Buffer> => {
  const doc = new PDFDocument({ margin: 48, size: "A4" });
  const chunks: Buffer[] = [];

  return await new Promise<Buffer>((resolve, reject) => {
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(22).text("Nudgr Friction Report", { align: "left" });
    doc.moveDown(0.4);
    doc.fontSize(11).fillColor("#555").text(`Template: ${data.reportType}`);
    doc.text(`Generated: ${formatDate(data.generatedAt)}`);
    doc.text(`User: ${data.userId}`);
    doc.text(`Date Range: ${formatDate(data.startDate)} → ${formatDate(data.endDate)}`);

    doc.moveDown();
    doc.fillColor("#111").fontSize(14).text("Executive Summary");
    doc.moveDown(0.3);
    doc.fontSize(11);
    doc.text(`• Total friction events: ${data.totalEvents}`);
    doc.text(`• Total error logs: ${data.totalErrors}`);
    doc.text(`• Critical errors: ${data.criticalErrors}`);
    doc.text(`• Average event severity: ${data.averageSeverity.toFixed(2)}`);

    doc.moveDown();
    doc.fontSize(14).text("Top Pages by Friction Volume");
    doc.moveDown(0.3);

    if (data.topPages.length === 0) {
      doc.fontSize(11).text("No page-level friction data found for this range.");
    } else {
      data.topPages.forEach((item, index) => {
        doc.fontSize(11).text(
          `${index + 1}. ${item.pageUrl} — ${item.events} events, avg severity ${item.avgSeverity.toFixed(2)}`
        );
      });
    }

    doc.moveDown();
    doc.fontSize(10).fillColor("#666").text(
      "This report was generated by the Railway backend export pipeline.",
      { align: "left" }
    );

    doc.end();
  });
};
