// This file is automatically generated. Do not edit it directly.
// Deprecated: Supabase has been fully replaced by the Railway backend API.
// Keep this module as a guardrail so any stale imports fail loudly at runtime.

const deprecatedMessage =
  "Supabase client is deprecated. Use '@/lib/apiClient' and Railway backend endpoints instead.";

export const supabase: Record<string, never> = new Proxy({} as Record<string, never>, {
  get() {
    throw new Error(deprecatedMessage);
  }
});